---
# Configure and start the SvxLink server
svxlink_runner_use_svxlink: true

# The language packs to install
svxlink_runner_langpacks:
  - lang: "en_US"
    name: "heather"
    url: "https://github.com/sm0svx/svxlink-sounds-en_US-heather/releases/download/19.09.99/svxlink-sounds-en_US-heather-16k-19.09.99.tar.gz"

# The hostname for the SvxReflector host
svxlink_runner_reflector_host: "reflector.example.org"

# String version of the CTCSS to TG map suitable to insert at the CTCSS_TO_TG
# SvxLink configuration variable
svxlink_runner_ctcss_to_tg: >-
  {%- set items = [] -%}
  {%- for ctcss, tg in (svxlink_runner_ctcss_to_tg_all|d({})).items() -%}
    {%- if tg > 0 -%}
      {{ items.append(ctcss|string + ':' + tg|string) }}
    {%- endif -%}
  {%- endfor -%}
  {{ items|join( ',' ) }}

# CTCSS to talkgroup map suitable for insertion into node_info.json
svxlink_runner_ctcss_to_tg_json: >-
  {%- set items=[] -%}
  {%- for ctcss, tg in svxlink_runner_ctcss_to_tg_all.items() -%}
  {{ items.append('"' + ctcss|string + '": ' + tg|string) }}
  {%- endfor -%}
  {{ "{" + items|join( ', ' ) + "}" }}
