---
- name: Set up server as ansible target
  hosts: all
  vars:
    ansible_become: True
    ansible_ssh_pipelining: False
  tasks:
  - name: Create ansible user
    user:
      name: "{{ ansible_target_user }}"
      comment: Ansible Automation User
      password: "*"
      shell: /bin/bash

  - name: Install SSH public key for ansible user
    authorized_key:
      user: "{{ ansible_target_user }}"
      state: present
      key: "{{ lookup('file', 'files/id_rsa.pub') }}"
      exclusive: True

  - name: Configure sudo for ansible user
    copy:
      content: |
        # SSH pipelining does not work with requiretty enabled
        Defaults:{{ ansible_target_user }} !requiretty

        # Let the ansible user execute any command as any user
        {{ ansible_target_user }}   ALL=(ALL:ALL) NOPASSWD: ALL
      dest: /etc/sudoers.d/ansible
      owner: root
      group: root
      mode: 0440
